language: python
python: '3.6'
branches:
  only:
  - master
  - develop
install:
  - pip install pytest coverage codacy-coverage
script:
  - printenv
  - ls -la
  - coverage run -m py.test tests
  - coverage xml
  - python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: devopshq
  password:
    secure: "c59mB1I6teHzX5vSs1k2VfEyntkQU8Y7o7pwAusygj/5M9sIPeKcveOfbIHj2E1ltQFpPT3wF8quHmyETYvKPXdfggZsm7pxdx+KfrveiMpGwnxaGVPjIXSTA4FC2pXP7DQK3+yzc61U7OM1k0skGg8N6Qs7fdFWAGKL+o3S6uW5cYgutTaj8uh8L4a7rxxR5VxvfK3jw5yLLnd7EWMN9tngVm4L1jUZsUvDKis7i+MNNynhgO0bln5s/uj/IPt+5rghcsiqFIgnmcVH0Nxe/f8iYnzMXFVqVISpj+XcV0EQBMw0xGjEdNGrc2rkCy9zw2GmNxM+JaUyXV+eEln+4vGz7tbZrdwMdasre2AKQMX+4jlt38W6nUV26txwTFkQ03oRcntSR8acYy/9WxOufkRT9Br/E10F6Axoadwn2zzdQEc6iuzZ32BvgqmS/AV+IutLFbmqwu5Gma9jzWQ1olE6me68ZZYEqTFf+iDe8uzfLPHmSUeCqXiehlN8v8tNjKjk1JSrOmuAWvoPxr2DGHBImEPCGM8TxOLx9IoqDMF0nEwuOqTmlvtJqv+JrA8q+rpkjeqnXUCXuRfM8eDP//b4syMdC9D2w4TV9eMg7FIgXvB3zMLKxGxZHXdNiFFpg5PvWithxdZf1YNIgyGknL6A+OrUSqIAhw3vxTXSZRg="
  distributions: bdist_wheel
  on:
    all_branches: true
  skip_cleanup: true
after_script:
  - echo "Deploy to PyPI finished."
env:
  global:
  - secure: "jEMGwLJ8Ri1Ik3gvDUYuYsOWLJ8F7Ta3MmbeX//FasbDHtVrcIunnCI9q1ispBGjU+fXNmCK4Booysvv5FPt2YbgUbEejp2Nfp/FnWGyHl0htDLeE3pBd9nzs6JD6swnLiAz0r6Ds1fsPloMcJwbAKEjEjwqBsPKZ51n1z28xt1960ybIt0fMXsZzCne4bCqpA2EeLMX2oWP5f+l5+18nJK5hog6L8+zAgxJU3OAscv7IqkMlgcqw6X+DQ2q9IZYdPEJy5fc/zuKgHJK6PbjDLm82jYYbr125W60G9McuP8VSC1rtc2WoWPgL70C5DD7Ba9NOszbTSxyDvx/DUtMQsCiR5KBAFap/BJvaZiFuATU6mwvU/VsPVNrltEDjdlXIpYar9X97Ue8hW+HuCp+l1CKNIM01QrPgLs3W1FxIYyufG1BDqzsGgYJnfjaw/zW9fX4CNUunkba4yC3C3913ef3qY11EIgVfMlQh/hdtWAvuwExBFnm21afhRtHkyVrKeI3oFB/Ws3CAqCSL/AWZoHARjfcRiUXFW2t2b75bEKXUoEbZ8hFr5GmUAC53zFNeMz8YQdzYqbS9r6lImlVESgixiMRgqDxpBUh+uBPalqqWKR/YRuKOoB2SluY6NtgizSZCapItfl7hK++lHHEk3w48h9cQ5pya9Lv1GVMpnQ="