language: python
python: '3.6'
branches:
  only:
  - master
  - develop
install:
  - pip install pytest
script:
  - ls -la
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    all_branches: true
  user: tim55667757
  password:
    secure: "h39nIBYf7KW1SASfahe/GXklpIOCij4WsoWDdktVDFijuviYHfjoAPmkCO6cZYpCMVhRKTh/SFTltutam4MHMCEnh3a7pEmxTgDs7pFIoYkcKrF/vDkhPyDuC/SqZtbRjUFgOGgiKBoMwRrWqdeFFmMN/XuDj//BBgAN3jF2WRalhqOr2NFtqX80HBZQPUU6MYFufqAvXva6rH0oWh69dDwFkCn+0TDvPBPf14ltLfs0szPfSjL/1GVtqGCsQ5auGr/AoQYfK7SyEm+qDiEGsi8yp/XdpwY+bLZiw8vRSrluk/VepQ/jfSGi/LReXlWLpbNAt6KWnOxwJtLEvjJ60cRoLHMdohY55R6BrD8/BIfcaeXA0cGm+cj2Iz8ckYNqN4xYFK45EtQC0T8ItHK6MF8tuWLJZXjnv4w3bn6LEuyaQjTjPlIS82pNOzGVniFcsVIp3cM5KKJgbf3g4zPcapHN9pyLLHcdwBrKbq3v2W3wyjeZHws6//QY+F2HqQbwLeP+EY23/6l2sYu6wruy4NkLCFGEeZpdkjoaVlJcN5U1OXCo+CYaAa9gh/kGAy89hBMZL1owYEtPCmdvOgxn//lBsmYAoYvmgG3yjNj2cRchrJzZodSoVQhpfuknPeFviDD6hbfemq6MW3d2ucQgmJ3ZjUM35T7Q6JBBfZTgyIs="
after_script:
  - echo "Deploy to PyPI finished."
