language: python
python: '3.6'
branches:
  only:
  - master
  - develop
install:
  - pip install pytest
script:
  - printenv
  - ls -la
deploy:
  provider: pypi
  user: Tim55667757
  password:
    secure: ftqEz1ThMpSVtae8BrAgteyZ7asCTcreoXxBGc5v0fNVDIPu/lMIlearOtxoUOqwHHGPRMyjh+/NgdzzrQx4YpoqKxzNE/0srBLKO+dD+UzF/V2UfbkK0Ak57GKUAP/rDFLjtasm1AAR8i/0erQbWur6q9g+Oi33wkGWDkljN96fvshllcVJc1pYOoyU2ijphZVrW7XF9Vcm9pZWIaro4ujzFBWJHkDCovtC4sdkYfbLk8Eboz7tmS/acqNKbB9ZKUgPg5gtC1oLFNynV935tqLN5sDY7wzJ1tINTAb/hZKn1dRbk7YiDM+el1nlGrQbU8xEgYqMm6eNCojgSKJq4ISbbcISIOXd4HfROYd//xy4w98QgL91d0rT57pIgJ9taC8agtigB5LwLDoR4E5T7yyQcWwbSjtnNqh14iHe0+sHpag9g0hI3VLgIzpnmw1OvKGMUSioOGpzAQYBprsqy/YWVrmRszdzEp4pFfKlfIMMmnMOf7LULxUdGZtEfDV+X+hYvOiFUXPuujbUrdZjH/e/9ttPl7OdctiR4WRQyayh+VowDqr2QTTXip5BiJsA+RGR/k+OHRwr/Bwu4wFYq5fDIal6+56c4uOL/oMb+El290mmBz42IJWsW7+33JBKF920056QFwFbpz8bGa8pUqoiKmUj4gBYnn0FwxC6C/M=
  on:
    distributions: sdist bdist_wheel
    all_branches: true
  skip_cleanup: true
after_script:
  - echo "Deploy to PyPI finished."
