language: python
python: '3.6'
branches:
  only:
  - master
  - develop
install:
  - pip install pytest
script:
  - ls -la
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    all_branches: true
  user: tim55667757
  password:
    secure: f7fPH1uYI/+FjlY0kuLyY2eDyzorVjZCHwdm5Vqm8oRyD9aq5dAML4lMVpVbB4N5+pDC8pzJieu9jJRX0E+RSbtdheiXSLGoov+CuR6esunkDKrP4ifae9J/4qD7DJZ3STkkwYdQLi0wu5UyfmZeMB6we5Hu4VMvptPLd4OBybZiUgHN4lR66/rx0Jze/FfMwJWPlHgdOu7xMa/XXs0Ss9LRfbmOct2hs8n8fsef9Etx9Z/5DAv5xUVfNjhsnQvuk1LTvQB7jIFQgEae9OBYreMKZWyyi76ZzFFIHtiYWd7yIep+Z0/E0dlyGJOdSamO3VaK6N1Tsvid6EKLhxNiUO3mJ2MxBtaCdUu2wHGePEiPoo7JBiVPEI5b36Sh7Pqa1FiQjtu07JcltWpj0K616PYhhDvQoOz2EDl1spRkVqsvYDc02OnYrfZw79pZ3d+wllarX+4MurgSHexWNaeC4o5Uq0wyHngUx8s0Iyk7xfDNqx6rGmvWCiuqsVymKozcSUefcwTEXo5ClwN72SNnf2uzGTPvfs3ju9Hmj56W/vXHymC3B4xKu7Jd24dQviRqpiSeF/+7bT6icJS/vDLF4xFhLP5GO/YO8n9u+0BWanr4b/WfxshRjODo6AHJzQ//Doa1bYNgf1TOrJLLXtN7Oa8+48M3z5dz9brKAGPuAHk=
after_script:
  - echo "Deploy to PyPI finished."
