language: python
python: '3.6'
branches:
  only:
  - master
  - develop
install:
  - pip install pytest
script:
  - ls -Rl
deploy:
  provider: pypi
  user: tim55667757
  password:
    secure: "uYB7+puYPnTVm4NDlwFyCo3g6jraAqli+xUaaGu79ogpmRmbH7PfJdk+V5XfoihdxFhiMjall4L9wDI9ROUlE1xAgWWpHS7qEkvrXsf8yaxdshjmcPvr/iVpRuE0peLKVqXElak7Nb5evhqrHyckTyxu0fRVjGSDJhrkTNeuJAblKHOvDnJYcWMSfT2scYLok6EvGEFL45BObwWjXWKSgrj8e+ukTV2oK5GgWJdIe096KuuZmlp9kCeYgH/AhvaRWcroKNvWriFlN0O65I0hr016y2tNIbv5lFhmCvnPinMt3Fiy81IARAXlaXTCnCiqFrDzhqPQV0EbhXHqJE7RoNR2pQpmFOwpgfeJPEinI4LhvVTOzZpNRDLglZ6nEavq+HDwoVQFmpAKvvSYRPvFbtgzl5Tng/Aa6FRM0SqH49nkChZDF/9WT2Y+/5JOD8ZQudveuWeu6Ih4wieHqF0aa5eJJQWqqFWs+H0dmcdH29yVU8amDiTkrgbbad9VGkK56vRUR8xchwLJdNykb6UYiOVbCXgyB0OyXrScb8ElyZcM3YXtKnJfooD7f4lBYklJAJBQ8v0ckvR62yls/Tmx0bUxS5XteYrt8Ni0hdTBhBVD+Dlk11b+brn+NomI9aGCF6nME9LXs3noiAm4jxtkaXc4pYpRAy0AvqucDytqDow="
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    all_branches: true
after_script:
  - echo "Deploy to PyPI finished."
