language: python
python: '3.6'
branches:
  only:
  - master
  - develop
install:
  - pip install pytest
script:
  - ls -l
deploy:
  provider: pypi
  user: tim55667757
  password:
    secure: "OTbR8Tmgby6SN5ysAiz5qqYtl3xtMKiIIAIX9wIVS8QhgGDa28mTxuQtyhnRW1sFkXSTq2yKocHBOE2ttoPVL4kWdoETLH5YDapIM3CysshKwk8V8UO84B2tDf0/wyB22bP8v9W0+6KEEMaektNGy8l4zGIDpfD0AfELk/FReMelbZvqTewhXdQos8YLA8VMbJC9YCK6OV3A2w49/hIFUCQmtjZ7NcIXTeGmXGx7+J4ZrVKTq91lUGJDMtocsl2MqHN4/L4u5/H5p81VPqk9qThz7Ovwia6p9v7QFdDsI7uHK02NYsuLA/qhRIUDyGFkf4jaMdCSM9tn801L5+lDPcQa/DrhDHI+AmxqVI1GIU5XyA4bQYHkqShNvoGKRjSJtimdChly+qzpd/MdxCOuwviulc8YuedtcplXXZRZGVzHkCyiQQ+6tjeb3jblT5Y28SmY76zqLaov7NhORbjYMcjac2EGDTF+1byWPaGKH4wus0/QxHoALCyF4bMQrJu3PiTiTdXsIaju13Gn9+qh0a0PqknI/ZfVIe6/sgWcsmOtqN5+7XHuFmCIrfBqSId846aW8gRg23h+aDB2XEVpRdUNAos8XvwCOxqIUHlqKFxOcNpVPnuGjh0gwhU/5Ce+s4sAWELox6cNWze/jqaDrJhSMF5MqVK7x8oUMJJEZJU="
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    all_branches: true
after_script:
  - echo "Deploy to PyPI finished."
