language: python
python: '3.6'
branches:
  only:
  - master
  - develop
install:
  - pip install pytest
script:
  - printenv
  - ls -la
deploy:
  provider: pypi
  user: tim55667757
  password:
    secure: "fENmBud1TfPrP9sHQT2ccjkqSI+AWRdjEEbLfLFuVdlBSW8DfRFTAGFyL+b65ft+qpDOEvesEZbHvQhp+Zwn492mH4FrnWRc9kAxpnIHkKn3bJOJmOPxaNngM1KKHgH89lMDjG3qLDImZuetH+UE3wHuQk1qkyJ8VvIV+ZWk0W5DsaFi8TXmFqNwWJIfLesf0nn9ndvTej87OhkaVrS0PavT6ri7XcSa11zXMkKNIwEFOqwoa0mlnqdRwvD7ZDRpSgCdh2W/Oii6azUcNk0Qd6X1hfkN3PxKDoGRhMF/QNZ3l7OcsHA35zwYOGQd6CX03b/gDPqtD2ZugvQ9EmzrDCO2AVhvzcnWQWPXvgGSUPsTfCXiktnX8ZVBMyje1Tq5bTw8m84Fx7eDJWbMNfNTPmhowYESiFEETqrom18XLSzA+6y5hS9NSRCVGSOz/C3YH6SpcMnnrs7MxgdBSaGktfPrnaAL9SFA2pgkCbF1XMhhBS6Wnb1PyOBr4JDMviT8ApDj4WmEuqROtaP36+4rhfO9e3eID0TwlOUWbOc9R08b9N22SCcDmCIxgLfYMfOz8i+ce++rUXgms0h0UVxEb48fK9bomPGUCBe/H7Gh1JRlpSmwkS5RNqLLwhTCKCCHbnPvwSCcrlwim+kxTzMhbECg3cCjQfmOTozD86zkBI0="
  on:
    distributions: sdist bdist_wheel
    all_branches: true
  skip_cleanup: true
after_script:
  - echo "Deploy to PyPI finished."
