language: python
python: '3.6'
branches:
  only:
  - master
  - develop
install:
  - pip install pytest
script:
  - printenv
  - ls -la
deploy:
  provider: pypi
  user: tim55667757
  password:
    secure: ZcM80iGkIQOcW/O65SVZr7zzrGlpQ1BFlYs91WpPVdjwhOMKRrxm4ME5Rx5tDlyN49Td6+lOIpOogZW+2FcRS0am/hM830j6A+IQffBk3cxhVAE8nvjuwTlYm1JXOUWfnzNbYrZ1wEZPPwCWBxf5vs54UzmONSvMAU9L9EsK4s5o+b2K1Sl+YvCOKyeKoS9WxFxIeog30D0no4hHRkPvBeoPfoNrS2VaOuNM+H+m+lXXKrf5ywLCAbzgS0Pr37oI8jKE2v8PP/fl3W11YwpWO+u4CQteBmgTDpkexowqypuJxkTI3Dvo0UOSGJfe0sIxpqkCqffrcQsFQk0m3gzkaVYXCKl/sO2TDwS95m+Did0YquOSSwaysEt40DxDRjVgy9Yy4Gt9fx892qK92ZN9HZLdIc46K+FkO3xmIpqJX/bwWVT7jjP8YLHOYYx/9SqR2AyiY4sg9+6C9wjQx/ICg/0KyPl6lQnKDPWCKJ2XCo3ThQZVBR1NK/aHlj3uvxXdd66LbXFXqZyZTOHXYBUpK/qCs3qd2aoDSCwnf+XwqfQBPui8AK4SGyYtZioKUFnExRnEnFSGWWybJHAswxvo+xWGY220cAiXWkM16qQjzgST3FcJ2jlcnjBLwLGicoQE+lNkJMkQNgE6eRtptHcfJnWSrETOWOQPmwjpt593AhA=
  on:
    distributions: sdist bdist_wheel
    all_branches: true
  skip_cleanup: true
after_script:
  - echo "Deploy to PyPI finished."
