language: python
python: '3.6'
branches:
  only:
  - master
  - develop
install:
  - pip install pytest
script:
  - ls -la
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    all_branches: true
  user: Tim55667757
  password:
    secure:
    - on9UOnHh+vdy5iOgVHd6CO1miLq0Q2FHE4DWFcER/zJ6UXeK2nVNOTPw82FGFG8jFL1s0xavHez8bbuM34gMLR9asyl5urXsR+r1uamcjqLvIkhz6rrxQ9lwv/6cAeihce9qk+2nfuHQWADd4aiYPqQ87ctsacYmi6mDTUNt+DOFKl982e1qDq9/wxJd7x06WCz05Qh+o4b2MLAJD/F7XLdrbIBDCpxlHJErOWrReeaN05iL7uqbG7IS9arHsIO2RtEjADzzdKrWoj69M94wJdmxceYRK4fyNDGB87byW8oViQvmaEBocdR4BiqR4qPLi+Jqhsi0havt4tkDv8tcIXl7E3SHRnl3zfyRIpZRGw+f1Z4f4+y/QMeB82gvf/V1hOQKVbhtT087N+olcz2tc33ao7uNeZkSQpe9OngouZISoN1FVGLXFau7NCX1YzjMrLFcE2OCEbfBn0zNZ9A3HWwbOPaIQBo6lJtEp1Q+rpPU1EGb9s0DE/fIYR3yPPdGZZua3qg6E93h9lCGWJrGFcbpoTiYzzuUdOO5DU+5ywnT3pTmoZtzV1nRF+nUOgZMKA/8qDHYrQ8AnSGcb+KY67g0ZKbSGcUH2+wzFDLchO+ddyJrJov+4tM/BhOGz5FwoEbwP50HONcZ6DoexuICe3Zta7GVNaEVYrk55Udy95U=
after_script:
  - echo "Deploy to PyPI finished."
